apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: my-replica-app
  labels:
    name: my-replica-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-replica-app
  template:
    metadata:
      labels:
        app: my-replica-app
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
          - containerPort: 80

